trigger:
- main

pool:
  name: default
  demands: agent.name
  vmImage: 'windows-latest'

stages:
- stage: DotnetBuild
  displayName: "ASP.NET WebAPI Build" 
  jobs:
   - job: BuildApplication
     displayName: "Build"
     steps:
     - task: DotNetCoreCLI@2
       inputs:
         azureSubscription: 'Free Trial(4c511d3d-421c-47bb-b545-0dcb345be265)'
         command: 'build'
         projects: 'MyWebApp.sln'

- stage: DotnetTest
  displayName: "ASP.NET WebAPI Test"
  jobs:
    - job: TestApplication
      displayName: "Test"
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          azureSubscription: 'Free Trial(4c511d3d-421c-47bb-b545-0dcb345be265)'
          command: 'test'
          projects: 'MyWebApp.sln'
          testRunTitle: 'ASP.NET WebAPI Tests'
          workingDirectory: '$(Build.SourcesDirectory)'